from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.utils import *
from prophecy.libs import typed_lit
from job.config.ConfigStore import *
from job.udfs.UDFs import *

def SQ_MDM_sc_CPCR_TOUCH_POINT_MDMX(spark: SparkSession, in0: DataFrame) -> DataFrame:
    return in0.select(
        col("ETL_REQ_NUM"), 
        col("CUST_IDENT"), 
        col("MRKT_CNTC_IDENT"), 
        col("RESP_IND"), 
        col("PRMO_EVNT_CDE"), 
        col("CNTC_DISP_CDE"), 
        col("CNTC_DISP_DTE"), 
        col("MRKTG_REC_TYP_CDE"), 
        col("VEH_ID"), 
        col("DEL_REC_DTE"), 
        col("MRKTG_SRC_ADD_DTTM"), 
        col("MRKTG_SRC_UPD_DTTM"), 
        col("MDL_YR_1"), 
        col("VEH_MAKE_CDE_1"), 
        col("VEH_MDL_CDE_1"), 
        col("VEH_SUB_MDL_CDE_1"), 
        col("MOI_SRC_ADD_DTTM_1"), 
        col("MDL_YR_2"), 
        col("VEH_MAKE_CDE_2"), 
        col("VEH_MDL_CDE_2"), 
        col("VEH_SUB_MDL_CDE_2"), 
        col("MOI_SRC_ADD_DTTM_2"), 
        col("MDL_YR_3"), 
        col("VEH_MAKE_CDE_3"), 
        col("VEH_MDL_CDE_3"), 
        col("VEH_SUB_MDL_CDE_3"), 
        col("MOI_SRC_ADD_DTTM_3"), 
        col("MDL_YR_4"), 
        col("VEH_MAKE_CDE_4"), 
        col("VEH_MDL_CDE_4"), 
        col("VEH_SUB_MDL_CDE_4"), 
        col("MOI_SRC_ADD_DTTM_4"), 
        col("MDL_YR_5"), 
        col("VEH_MAKE_CDE_5"), 
        col("VEH_MDL_CDE_5"), 
        col("VEH_SUB_MDL_CDE_5"), 
        col("MOI_SRC_ADD_DTTM_5"), 
        col("MDL_YR_6"), 
        col("VEH_MAKE_CDE_6"), 
        col("VEH_MDL_CDE_6"), 
        col("VEH_SUB_MDL_CDE_6"), 
        col("MOI_SRC_ADD_DTTM_6"), 
        col("MDL_YR_7"), 
        col("VEH_MAKE_CDE_7"), 
        col("VEH_MDL_CDE_7"), 
        col("VEH_SUB_MDL_CDE_7"), 
        col("MOI_SRC_ADD_DTTM_7"), 
        col("MDL_YR_8"), 
        col("VEH_MAKE_CDE_8"), 
        col("VEH_MDL_CDE_8"), 
        col("VEH_SUB_MDL_CDE_8"), 
        col("MOI_SRC_ADD_DTTM_8"), 
        col("ETL_WFLOW_RUN_ID"), 
        col("SRC_FILE_NAME"), 
        col("SRC_SYSTM_CDE"), 
        col("ADD_DTTM"), 
        col("ADD_BY_USER"), 
        col("UPD_DTTM"), 
        col("UPD_BY_USER")
    )
